### ISSUE TITLE
Please how would you inject this into a nestjs service?

### ISSUE THREAD

**Issue by omozokelvin** [fuadop/sendchamp-sdk#6]
I am getting the below error

{
    "message": "sendchamp_sdk_1.default is not a constructor",
    "errors": "sendchamp_sdk_1.default is not a constructor",
    "status": 500,
    "success": false
}

**Comment by fuadop** [comment]
Hi @omozokelvin 👋🏾 , are you on the latest version ?

**Comment by omozokelvin** [comment]
Yes I am on the latest version and it's a NestJS application, i got it working via the native implementation without this SDK. NestJS supports dependency injection

**Comment by fuadop** [comment]
Hi @omozokelvin , add to your nestjs project tsconfig.json file: 

```json
esModuleInterop: true
```

cc: https://stackoverflow.com/a/64213538

Just tested that, and it worked in a test nestjs application I created just now.

**Comment by fuadop** [comment]
This needs to be added to the readme, for anyone using typescript.
