### ISSUE TITLE
SDK Update

### ISSUE THREAD

**Issue by peoray** [fuadop/sendchamp-sdk#65]
It seems that there have been updates to the Sendchamp API and the SDK needs to be updated. The most notable in my experience is the response to SMS. I used this yesterday and this is the response I got from the API

```
{
  code: 200,
  data: {
    business_id: '5928f6a8-063b-44d0-932c-63ac7b2afc3f',
    total_contacts: 1,
    created_at: '2023-06-21T13:49:38.875515631Z',
    updated_at: '2023-06-21T13:49:38.875515701Z'
  },
  errors: null,
  message: 'sent',
  status: 'success'
}
```

This is different from the `SendSMSResponse` and `SMSResponseData` interfaces. 

Also, route is required even though it says it isn't as a default value is set but if you make a request without it, it returns a `400` status.

There's a possibility that this is the case for all channels but since I only needed SMS to work, that  was the only channel I tested

Great work on the library :)

**Comment by igmrrf** [comment]
Good Day, been almost a year you logged this.

Just came across the package and will try to update it to the latest configurations available on the https://sendchamp.readme.io/ documentation.
